### PR TITLE
Fixes a typo in th first basic example

### PR DESCRIPTION
**Pull request by MaStr**

### CODE REVIEW

**Comment by Dunbaratu** [comment]
this version of the docs is defunct now

**Comment by MaStr** [comment]
I followed the doc link of the repository  https://github.com/KSP-KOS/KOS

Can you change & remove the link/webpage?
Where are the most recent docs?

**Comment by Dunbaratu** [comment]
Where?  That repository no longer links here.
If you click the word 'documentation' you end up here now: http://ksp-kos.github.io/KOS_DOC/

**Comment by Dunbaratu** [comment]
I'd like to know where you found the stale link that still points here so we can fix it, but the place you claim you found it already was changed quite a while ago.

**Comment by MaStr** [comment]
Before starting to contribute, I try to get an impression, how to contribute correctly. 

Sorry, I found it here in this issue
    https://github.com/KSP-KOS/KOS_DOC/issues/21 

I read it like "push changes here and I'll port it to the mainpage"

**Comment by Dunbaratu** [comment]
That was true once, and I fixed it in that issue just now, but that still leaves the question of what linked you to the KSP-KOS/KOS_DOC repository in the first place.

**Comment by MaStr** [comment]
https://github.com/KSP-KOS/KOS -->  README.md --> 
     Documentation : http://ksp-kos.github.io/KOS_DOC/

**Comment by Dunbaratu** [comment]
That's the same thing you referred to the first time.
 http://ksp-kos.github.io/KOS_DOC.is the new documentation.  It is not built from https://github.com/KSP-KOS/KOS_DOC/ at all.  we're just using the .io domain to host it.

**Comment by MaStr** [comment]
But both is wrong.
The readme should point me to http://ksp-kos.github.io/KOS/

**Comment by Dunbaratu** [comment]
One is the temp develop version of the other.  Both are built from the main repository's doc/ folder and not from KOS_DOC's code.  As far as I know, there is nothing anywhere that is still telling people to make issues with KOS_DOC.

**Comment by MaStr** [comment]
The structure of github pages, as far as I understood:
  http://<user>.github.io/<repository>/

See https://help.github.com/articles/user-organization-and-project-pages/

That means, you are pointing in your readme to wrong one, when you say "KOS" contains the latest version of the doku. Or is it the other way around.

I propose to delete the DOC_DEV thingy, if it isn't needed anymore.

(BTW: I found out, that I edited the wrong file anyway).

**Comment by Dunbaratu** [comment]
No, it makes sense.  You're reading the develop branch's readme.md, not the master's.  So it points at the place where we're hosting the develop docs, not the master docs.

What it's not supposed to be doing is telling you to use that fork as the place to edit the docs.  It's just being used to host their HTML rendered output.

The problem is entirely github's fault.  Even though they're supposed to allow you multiple branches of the source files that the docs are built from (i.e. a develop and a master branch), they still designed the hosting system at the .io domain such that there's only ONE branch that gets hosted and that's the branch called gh-pages.  So the problem is we have two branches in which the docs's sources live - develop and master, but only one branch to host them in - gh-pages.  So we hosted the develop version over on a separate fork, since we can't get github to have a gh-pages-master and a gh-pages-develop.

**Comment by MaStr** [comment]
ok, agreed. 

One final thing: 

  * maybe point our discussion out in the http://ksp-kos.github.io/KOS_DOC/contribute.html page, like "do PR to KSP-KOS/KOS:develop "

and one question: Why do you have the develop branch as a default branch on KSP/KOS and not master? That would point -at least- to the right documentation. I assume you are doing a normal branching & release cycle.

**Comment by Dunbaratu** [comment]
Because the default branch is the one that always appears when you first click the "crate pull request" button. We don't want people making pull requests into master. only into develop.  And it's a PITA to use the github interface for pull requests into a different branch than the default one, because you still have to sit there and wait for it to expensively form a useless diff report against the wrong (default master) branch betore you then get to the point where you can click the links to change which fork you're pulling it into, which makes it go back and recalculate the diff report again.  It's better to just be on the correct branch for forks to begin with.

It might be a good idea to change the readme to point at master's gh-pages and make the developrs have to go to the develop pages by hand-editing the URL, but it's not a good idea to make master branch the default.  We kept getting people making PR's against master when we did that, and often for things that were *already* fixed in develop but not released yet.

**Comment by MaStr** [comment]
I find it interesting, that you made such a experience and that point of view. Personally, I want to see the code, which I'm using while working with the (stable) software right after clicking on the repository.
 Well on PirateBoxDev we don't get much PRs, but after telling the requester once, that it is the wrong branch, they fix & resubmit it without alot discussion.

Maybe it is more like the target audience of the Repository.

Thanks for explaining that. 
best regards

**Comment by Dunbaratu** [comment]
Keep in mind it's not just the desire to get people to branch from develop and work there.  It's the fact that github does expensive work under the *assumption* you want to merge pull requests into the default branch *before* you get the user interface option to change the branch you're merging into.  So if you set your default branch to the one where you *don't* actually do the active work, then you're waiting for all that crud every time, uselessly.

**Pull request closed without merging**
